name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - name: Run tests
        run: |
          cd test
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/tb.vcd
            test/results.xml

      - name : Upload CORDIC plots 
        if : always()
        uses: actions/upload-artifact@v4
        with:
          name: cordic-plots-trigonometric
          path: artifacts/cordic/* 
          if-no-files-found: ignore
          retention-days: 14

      - name: Add plots to job summary
        if: always()
        shell: bash
        run: |
          echo "## CORDIC sweep" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          for img in artifacts/cordic/*.png; do
            [ -f "$img" ] || continue
            echo "<details><summary>$(basename "$img")</summary>" >> "$GITHUB_STEP_SUMMARY"
            echo "<img src=\"data:image/png;base64,$(base64 -w0 "$img")\" alt=\"$(basename "$img")\" />" >> "$GITHUB_STEP_SUMMARY"
            echo "</details>" >> "$GITHUB_STEP_SUMMARY"
          done